package:
  name: mmtfPyspark
  version: "0.1"

source:
  git_url: https://github.com/sbl-sdsc/mmtf-pyspark

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
    - pyspark
    - Biopython
    - msgpack-python
    - mmtf-python
    - sympy
    - requests
  run:
    - python
    - numpy x.x
    - pyspark
    - Biopython
    - msgpack-python
    - mmtf-python
    - sympy
    - requests

test:
  imports:
    - mmtfPyspark

about:
  hone: https://github.com/sbl-sdsc/mmtf-pyspark
  license: Apache License 2.0
